"Total Investment by Client";
SELECT ClientName,SUM(Quantity * PurchasePrice) AS TotalInvestment FROM Trades JOIN Clients ON Trades.ClientID = Clients.ClientID GROUP BY ClientName;
"Sector Allocation Analysis";
SELECT Sector, SUM(Quantity * PurchasePrice) AS TotalInvestment FROM Trades JOIN Assets ON Trades.AssetID = Assets.AssetID GROUP BY Sector ORDER BY TotalInvestment DESC;
"Largest Investor";
SELECT ClientName,SUM(Quantity * PurchasePrice) AS TotalInvestment FROM Trades JOIN Clients ON Trades.ClientID = Clients.ClientID GROUP BY ClientName ORDER BY TotalInvestment DESC;
create table MarketPrice AssetID INTEGER, CurrentPrice REAL);
insert into MarketPrice values (1,180),(2,350),(3,165),(4,35),(5,110),(6,155),(7,63),(8,700);
"Portfolio Current Value";
SELECT ClientName,SUM(Quantity * CurrentPrice) AS CurrentValue FROM Trades JOIN Clients ON Trades.ClientID = Clients.ClientID JOIN MarketPrices ON Trades.AssetID = MarketPrices.AssetID GROUP BY ClientName ORDER BY CurrentValue DESC;
"Profit or Loss by Client";
SELECT ClientName,SUM(Quantity * CurrentPrice) AS CurrentValue,SUM(Quantity * PurchasePrice) AS Cost,SUM(Quantity * CurrentPrice)- SUM(Quantity * PurchasePrice) AS ProfitOrLoss FROM Trades JOIN Clients ON Trades.ClientID = Clients.ClientID JOIN MarketPrices ON Trades.AssetID = MarketPrices.AssetID GROUP BY ClientName ORDER BY ProfitOrLoss DESC;
"Profit or Loss by Asset";
SELECT Ticker,SUM(Quantity * CurrentPrice)- SUM(Quantity * PurchasePrice) AS ProfitOrLoss FROM Trades JOIN Assets ON Trades.AssetID = Assets.AssetID JOIN MarketPrices ON Trades.AssetID = MarketPrices.AssetID GROUP BY Ticker ORDER BY ProfitOrLoss DESC;
"Ranking of investors";
SELECT ClientName,SUM(Quantity * PurchasePrice) AS TotalInvestment, RANK() OVER (ORDER BY SUM(Quantity * PurchasePrice) DESC) AS InvestorRank FROM Trades JOIN Clients ON Trades.ClientID = Clients.ClientID GROUP BY ClientName;
"Highest Return %";
WITH PortfolioSummary AS (SELECT ClientName,SUM(Quantity * PurchasePrice) AS Cost, SUM(Quantity * CurrentPrice) AS CurrentValue FROM Trades JOIN Clients ON Trades.ClientID = Clients.ClientID JOIN MarketPrices ON Trades.AssetID = MarketPrices.AssetID GROUP BY ClientName) SELECT ClientName, Cost, CurrentValue, CurrentValue - Cost AS ProfitOrLoss, ROUND(((CurrentValue - Cost) * 100.0 / Cost),2) AS Returnpct FROM PortfolioSummary ORDER BY Returnpct DESC;
"client rankings based on performance";
WITH PortfolioSummary AS (SELECT ClientName,SUM(Quantity * PurchasePrice) AS Cost, SUM(Quantity * CurrentPrice) AS CurrentValue FROM Trades JOIN Clients ON Trades.ClientID = Clients.ClientID JOIN MarketPrices ON Trades.AssetID = MarketPrices.AssetID GROUP BY ClientName)SELECT ClientName,ROUND(((CurrentValue - Cost) * 100.0 / Cost),2) AS ReturnPct,RANK() OVER (ORDER BY((CurrentValue - Cost) * 100.0 / Cost) DESC) AS PerformanceRank FROM PortfolioSummary;
"Asset Performance Report";
WITH AssetPerformance AS (SELECT Ticker,SUM(Quantity * PurchasePrice) AS Cost, SUM (Quantity * CurrentPrice) AS CurrentValue FROM Trades  JOIN Assets  ON Trades.AssetID = Assets.AssetID JOIN MarketPrices  ON Trades.AssetID = MarketPrices.AssetID GROUP BY Ticker) SELECT Ticker,Cost,CurrentValue,CurrentValue - Cost AS ProfitOrLoss,ROUND(((CurrentValue - Cost) * 100.0 / Cost),2)  AS ReturnPct FROM AssetPerformance ORDER BY ReturnPct DESC;
"Assets rank";
WITH AssetPerformance AS (SELECT Ticker,SUM(Quantity * PurchasePrice) AS Cost,SUM(Quantity * CurrentPrice) AS CurrentValue FROM Trades  JOIN Assets  ON Trades.AssetID = Assets.AssetID JOIN MarketPrices  ON Trades.AssetID = MarketPrices.AssetID GROUP BY Ticker)SELECT Ticker,ROUND(((CurrentValue - Cost) * 100.0 / Cost),2) AS ReturnPct, RANK() OVER (ORDER BY((CurrentValue - Cost) * 100.0 / Cost) DESC) AS AssetRank FROM AssetPerformance;
"Sector Performance Analysis";
WITH SectorPerformance AS (SELECT Sector,SUM(Quantity * PurchasePrice) AS Cost, SUM(Quantity * CurrentPrice) AS CurrentValue FROM Trades JOIN Assets  ON Trades.AssetID = Assets.AssetID JOIN MarketPrices ON Trades.AssetID = MarketPrices.AssetID GROUP BY Sector)SELECT Sector,Cost,CurrentValue,CurrentValue - Cost AS ProfitOrLoss,ROUND(((CurrentValue - Cost) * 100.0 / Cost),2) AS ReturnPct FROM SectorPerformance ORDER BY ReturnPct DESC;
"Sector Ranking";
WITH SectorPerformance AS (SELECT Sector,SUM(Quantity * PurchasePrice) AS Cost, SUM(Quantity * CurrentPrice) AS CurrentValue FROM Trades  JOIN Assets  ON Trades.AssetID = Assets.AssetID JOIN MarketPrices  ON Trades.AssetID = MarketPrices.AssetID GROUP BY Sector)SELECT Sector,ROUND(((CurrentValue - Cost) * 100.0 / Cost),2) AS ReturnPct, RANK() OVER (ORDER BY((CurrentValue - Cost) * 100.0 / Cost) DESC) AS SectorRank FROM SectorPerformance;
"Portfolio Concentration";
SELECT Sector,ROUND(SUM(Quantity * PurchasePrice) * 100.0 /(SELECT SUM(Quantity * PurchasePrice) FROM Trades),2) AS AllocationPct FROM Trades JOIN Assets  ON Trades.AssetID = Assets.AssetID GROUP BY Sector ORDER BY AllocationPct DESC;